---
# ReadTheDocs Config file.
# See https://docs.readthedocs.io/en/stable/config-file/v2.html
# Needed because our project requirements.txt file
# does not include documentation packages.
version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
sphinx:
   configuration: docs/conf.py
python:
   install:
   - requirements: build-requirements.txt
